#!/bin/bash
AUTO_SET_WAN_INTERFACE="true"
if [[ $AUTO_SET_WAN_INTERFACE == "true" ]];then
  ETH_LIST=$(ifconfig | grep Ethernet | awk -F " " '{print $1}')
  PCIE_ETH_LIST=""
  for ETH in ${ETH_LIST}
  do
    BUS_ID=$(ethtool -i "$ETH" | grep bus-info | awk -F ":" '{print $2}')
  # 获取所有非usb网卡接口名称
    if [[ $BUS_ID != " N/A" && $(echo "$BUS_ID" | grep usb) == "" ]];then
      PCIE_ETH_LIST="$PCIE_ETH_LIST $ETH"
    fi
  done
  # 网卡接口名称正序排列
  # shellcheck disable=SC2207
  SORTED_PCIE_ETH_LIST=($(echo "$PCIE_ETH_LIST" | tr ' ' '\n' | sort))
  #取第一个网卡接口名称
  FIRST_ETH=${SORTED_PCIE_ETH_LIST[0]}
  # 第一个网卡接口名称不为空字符串,则将默认的eth0和第一个网卡接口名称交换
  if [[ $FIRST_ETH != "" ]];then
      sed -i "s/option device 'eth0'/option device '""${FIRST_ETH}""'/g" /etc/config/network
      sed -i "s/list ports '""${FIRST_ETH}""'/list ports 'eth0'/g" /etc/config/network
      /etc/init.d/network restart
  fi
fi